# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160621_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='slug',
        ),
    ]
