# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160622_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(default='harsh'),
        ),
    ]
