# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20160624_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishliked',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishliked',
            name='like',
        ),
        migrations.RemoveField(
            model_name='dishliked',
            name='user',
        ),
        migrations.DeleteModel(
            name='DishLiked',
        ),
    ]
