# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20160624_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='dish',
            new_name='title',
        ),
    ]
