# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20160627_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='company',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
