# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_likeunlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
