# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_paper_like_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-like_count', '-year']},
        ),
        migrations.AddField(
            model_name='paper',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='paper',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
